#!/usr/bin/env bash
#Configure my Nginx server so that /redirect_me is redirecting to another page.
sed  '/server_name _;/a \\tlocation = /redirect_me/ {\n\t\treturn 301 http://topbally.tech;\n\t}' /etc/nginx/sites-available/default
service nginx reload
