#!/usr/bin/env bash
#Configure my Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed  '/server_name _;/a \\tlocation = /redirect_me/ {\n\t\treturn 301 http://topbally.tech;\n\t}' /etc/nginx/sites-available/default
service nginx reload
