#!/usr/bin/env bash
#Configure my Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i  '/server_name _/a\\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page." > /var/www/html/404.html
sed -i '/# pass PHP/i\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
service nginx restart
