#!/usr/bin/env bash
#Bash script that generates a MySQL dump and creates a compressed archive out of it.
sudo mysqldump --all-databases -u root -p"$1" > backup.sql
sudo tar -czvf $(date +"%d-%m-%Y.tar.gz") backup.sql
