#!/usr/bin/env bash
# This script is displaying "Best School" 8 times while displaying 'goodluck'
# and badluck for the 8th and 4th loop respectively.
i="0"
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
