#!/usr/bin/env bash
#Bash script to reload Gunicorn in a graceful way

# Send a HUP signal to the gunicorn Master processes
# (ie those with a parent process ID of 1)
#kill -HUP "$(pgrep 'gunicorn' -P 1)"
pgrep gunicorn | xargs kill -HUP
